services:
  db:
    image: postgres:15-alpine
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: