services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:example@db:5432/dev-db
      - NODE_ENV=production
    restart: always

  db:
    image: postgres:15-alpine
    env_file:
      - .env  # Load environment variables from .env file
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
      - POSTGRES_DB=dev-db

volumes:
  db_data: